# Generated by Django 4.2.3 on 2023-08-27 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=12, null=True, unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('elements', models.JSONField(null=True)),
            ],
            options={
                'permissions': (('can_set_role_0', 'Allows promotion to role OWNER'), ('can_set_role_1', 'Allows promotion to role ADMIN'), ('can_set_role_2', 'Allows promotion to role WRITER'), ('can_set_role_3', 'Allows promotion to role READER'), ('can_modify_0', 'Allows modifying roles of people currently OWNER'), ('can_modify_1', 'Allows modifying roles of people currently ADMIN'), ('can_modify_2', 'Allows modifying roles of people currently WRITER'), ('can_modify_3', 'Allows modifying roles of people currently READER')),
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('permission', models.IntegerField(choices=[(0, 'Owner'), (1, 'Admin'), (2, 'Writer'), (3, 'Reader')], default=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('owner', 'Owner'),),
                'unique_together': {('user', 'board')},
            },
        ),
        migrations.CreateModel(
            name='BoardSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='users',
            field=models.ManyToManyField(related_name='boards', through='boards.Participation', to=settings.AUTH_USER_MODEL),
        ),
    ]
