# Generated by Django 4.0.6 on 2022-10-12 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateTimeField(auto_now=True)),
                ('permission', models.IntegerField(choices=[(0, 'Owner'), (1, 'Admin'), (2, 'Writer'), (3, 'Reader')], default=3)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userparticipation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userparticipation',
            name='board',
        ),
        migrations.RemoveField(
            model_name='userparticipation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='board',
            name='guests',
        ),
        migrations.AlterField(
            model_name='board',
            name='users',
            field=models.ManyToManyField(related_name='boards', through='core.Participation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='GuestParticipation',
        ),
        migrations.DeleteModel(
            name='UserParticipation',
        ),
        migrations.AddField(
            model_name='participation',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.board'),
        ),
        migrations.AddField(
            model_name='participation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('user', 'board')},
        ),
    ]
