# Generated by Django 4.1.3 on 2022-11-28 19:16

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_config_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='config_set',
            field=models.ForeignKey(default=core.models.get_a_configuration_set, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.configurationset'),
        ),
    ]
