# Generated by Django 4.1.4 on 2023-03-29 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'permissions': (('set_role_3', 'Allows setting user role to READER'), ('set_role_2', 'Allows setting user role to WRITER'), ('set_role_1', 'Allows setting user role to ADMIN'), ('set_role_0', 'Allows setting user role to OWNER'))},
        ),
    ]
