# Generated by Django 4.1.4 on 2023-05-12 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_board_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'permissions': (('can_set_role_0', 'Allows promotion to role OWNER, ADMIN, WRITER, READER'), ('can_modify_0', 'Allows modifying roles of people currently OWNER, ADMIN, WRITER, READER'))},
        ),
    ]
