# Generated by Django 4.1.4 on 2023-05-12 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_board_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'permissions': (('can_set_role_0', 'Allows promotion to role OWNER'), ('can_set_role_1', 'Allows promotion to role ADMIN'), ('can_set_role_2', 'Allows promotion to role WRITER'), ('can_set_role_3', 'Allows promotion to role READER'), ('can_modify_0', 'Allows modifying roles of people currently OWNER'), ('can_modify_1', 'Allows modifying roles of people currently ADMIN'), ('can_modify_2', 'Allows modifying roles of people currently WRITER'), ('can_modify_3', 'Allows modifying roles of people currently READER'))},
        ),
    ]
